version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - app-network
        depends_on:
            - db
            - redis
        environment:
            - DB_CONNECTION=mysql
            - DB_PORT=3306
            - DB_HOST=db
            - DB_DATABASE=laravel
            - DB_USERNAME=root
            - DB_PASSWORD=root
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379

    db:
        image: mysql:8.0
        container_name: laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - app-network

    redis:
        image: redis:alpine
        container_name: laravel-redis
        ports:
            - 6379:6379
        networks:
            - app-network

    webserver:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 8000:80
        networks:
            - app-network
        depends_on:
            - app

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
