---
- name: Log VM creation start
  debug:
    msg: "About to create VM {{ vmname }}..."
- name: Create new VM
  shell: multipass launch --name {{ vmname }} --cloud-init cloud-init.yaml {{ vmcreationparams }}
  delegate_to: localhost
- name: Log VM creation completion
  debug:
    msg: "Finished creating VM {{ vmname }}."
